<eclipse>
<message date="1/1/0" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/0" time="0.00000000000000">
 LICENSE ERROR  -1 FOR MULTI-SEGMENT WELL OPTION                         
 FEATURE IS INVALID. CHECK YOUR LICENSE FILE AND                         
 THE LICENSE LOG FILE                                                    
</error>
</eclipse>
