<eclipse>
<message date="1/1/0" time="0.00000000000000">
 RESOPT   IS NOT AVAILABLE IN ECLIPSE 100                                
 AND HAS BEEN IGNORED                                                    
</message>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/1990" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
