<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE FIELD    KEYWORD                                   
  6 /                                                                    
</warning>
<error date="1/1/1990" time="0.00000000000000">
 TRPLPORO HAS BEEN SPECIFIED BUT                                         
 DUALPERM HAS BEEN USED FIRST.                                           
 THESE FEATURES ARE NOT COMPATIBLE                                       
 IN THIS RELEASE. TRIPLE POROSITY                                        
 HAS BEEN DISABLED                                                       
</error>
<warning date="1/1/1990" time="0.00000000000000">
  NODPCO HAS NO EFFECT IN ECLIPSE 100                                    
</warning>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/1990" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
